name: "composition"
explore_method: "null"
exploit_method: "sfgpi"
entropy_tuning: True
alpha: 1.
alpha_lr: 3e-4
lr: 0.002236613447518631 
policy_lr: 0.006458911999719074 
gamma: 0.99
tau: 5e-3
td_target_update_interval: 1
updates_per_step: 1
reward_scale: 1.0
grad_clip: null
value_net_kwargs: 
    hidden_dim: 64
    num_layers: 4
    resnet: False
    layernorm: False
    fta: False
policy_net_kwargs: 
    hidden_dim: 32
    num_layers: 4
    resnet: False
    layernorm: False
    fta: False
    
augmentHeads: True
norm_task_by_sf: True