name: "dac"
entropy_tuning: True
alpha: 1.
alpha_lr: 3e-4
lr: 0.009145
policy_lr: 0.001234
gamma: 0.99
tau: 5e-3
td_target_update_interval: 1
updates_per_step: 1
reward_scale: 1.0
grad_clip: null
value_net_kwargs: 
    sizes: [64, 64]
    activation: "relu"
    layernorm: True
policy_net_kwargs: 
    sizes: [32, 32]
    layernorm: False